// <auto-generated />
using BooksApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksApi.Data.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BooksApi.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Library")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BooksApi.Models.Book", b =>
                {
                    b.OwnsOne("Ally", "Partner", b1 =>
                        {
                            b1.Property<int>("BookId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Instructions")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.ToJson("Partner");

                            b1.WithOwner()
                                .HasForeignKey("BookId");

                            b1.OwnsMany("ConversationHistory", "History", b2 =>
                                {
                                    b2.Property<int>("AllyBookId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Answer")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Question")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AllyBookId", "Id");

                                    b2.ToTable("Books");

                                    b2.WithOwner()
                                        .HasForeignKey("AllyBookId");
                                });

                            b1.Navigation("History");
                        });

                    b.Navigation("Partner");
                });
#pragma warning restore 612, 618
        }
    }
}
