// <auto-generated />
using BooksApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksApi.Data.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20240822104349_m2_library")]
    partial class m2_library
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BooksApi.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Library")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Max",
                            Description = "Nursing",
                            Library = "Kalista",
                            Name = "Tom"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Fay",
                            Description = "Mining",
                            Library = "Kalista",
                            Name = "Ann"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Sun",
                            Description = "Nursing",
                            Library = "Kalista",
                            Name = "Joe"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Fox",
                            Description = "Computing",
                            Library = "Kalista",
                            Name = "Sue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
